name: Deploy

env:

  GKE_CLUSTER: joshlong-com
  GKE_ZONE: us-central1-c
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

  SPRING_RABBITMQ_HOST: ${{ secrets.SPRING_RABBITMQ_HOST }}
  SPRING_RABBITMQ_PASSWORD: ${{ secrets.SPRING_RABBITMQ_PASSWORD }}
  SPRING_RABBITMQ_PORT: ${{ secrets.SPRING_RABBITMQ_PORT }}
  SPRING_RABBITMQ_USERNAME: ${{ secrets.SPRING_RABBITMQ_USERNAME }}
  SPRING_RABBITMQ_VIRTUAL_HOST: ${{ secrets.SPRING_RABBITMQ_VIRTUAL_HOST }}

  SPRINGTIPS_GITHUB_REBUILD_KEY: ${{ secrets.SPRINGTIPS_GITHUB_REBUILD_KEY }}
  SPRINGTIPS_FONTS_ENCRYPTION_PASSWORD: ${{ secrets.SPRINGTIPS_FONTS_ENCRYPTION_PASSWORD }}
  SPRINGTIPS_FONTS_ENCRYPTION_SALT: ${{ secrets.SPRINGTIPS_FONTS_ENCRYPTION_SALT }}

  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

  SPRING_R2DBC_PASSWORD: ${{ secrets.SPRING_R2DBC_PASSWORD }}
  SPRING_R2DBC_USERNAME: ${{ secrets.SPRING_R2DBC_USERNAME }}
  SPRING_R2DBC_URL: ${{ secrets.SPRING_R2DBC_URL }}

  SPRINGTIPS_TWITTER_USERNAME: ${{ secrets.SPRINGTIPS_TWITTER_USERNAME }}
  SPRINGTIPS_TWITTER_CLIENT_ID: ${{ secrets.SPRINGTIPS_TWITTER_CLIENT_ID }}
  SPRINGTIPS_TWITTER_CLIENT_SECRET: ${{ secrets.SPRINGTIPS_TWITTER_CLIENT_SECRET }}

#  TWITTER_CLIENTS_SPRINGTIPS_CLIENT_ID: ${{ secrets.TWITTER_CLIENTS_SPRINGTIPS_CLIENT_ID }}
#  TWITTER_CLIENTS_SPRINGTIPS_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENTS_SPRINGTIPS_CLIENT_SECRET }}
#  BOOTIFUL_TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENTS_SPRINGTIPS_CLIENT_ID }}
#  BOOTIFUL_TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENTS_SPRINGTIPS_CLIENT_SECRET }}


on:
  push:
    branches: [ main ]


jobs:
  build-and-deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    name: Setup and Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER  }}'
          location: '${{ env.GKE_ZONE }}'

      - run: |
          gcloud config set project $PROJECT_ID
          gcloud --quiet auth configure-docker
          kubectl get pods

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: joshlong/java-version-export-github-action@v20

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_MAJOR_VERSION }}

      - name: Deploy Site
        run: |
          cd $GITHUB_WORKSPACE
          export ROOT_DIR=$GITHUB_WORKSPACE
          ./deploy/deploy.sh
